# https://towardsdatascience.com/working-with-apis-using-flask-flask-restplus-and-swagger-ui-7cf447deda7f

from flask import Flask, request
from flask_restx import Api, Resource, fields

app = Flask(__name__)
api = Api(app=app, 
          version="0.1", 
          title="Income inference endpoint", 
          description="Calcula el ingreso de un cliente dada informacion proporcionada por el BC")

high_income = api.namespace('high/api/v1', description='Predicts an income score given a feature vector for high-income clients')
medium_income = api.namespace('medium/api/v1', description='Predicts an income score given a feature vector for medium-income clients')
low_income = api.namespace('low/api/v1', description='Predicts an income score given a feature vector for low-income clients')

model_fields = api.model('Model parameters', 
                        {'Avg_hC_R_open': fields.Float(required = True, 
                                                        description="Promedio de high credit para cuentas revolventes abiertas", 
                                                        help="to_be_filled"),
                            'Avg_lc_sm2_12m_o': fields.Float(required = True, 
                                                        description="Promedio del límite de crédito sin MOP 2 o mayor en los últimos 12 meses para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'Avg_lc_sm2_12m_u': fields.Float(required = True, 
                                                        description="Promedio del límite de crédito sin MOP 2 o mayor en los últimos 12 meses para cuentas útiles", 
                                                        help="to_be_filled"),
                            'Avg_meses_cta': fields.Float(required = True, 
                                                        description="Promedio en meses en cuentas", 
                                                        help="to_be_filled"),
                            'Avg_meses_cta_open': fields.Float(required = True, 
                                                        description="Promedio en meses en cuentas abierta", 
                                                        help="to_be_filled"),
                            'Avg_saldo': fields.Float(required = True, 
                                                        description="Saldo Promedio", 
                                                        help="to_be_filled"),
                            'Avg_saldo_R_open': fields.Float(required = True, 
                                                        description="Saldo Promedio para cuentas revolventes abiertas", 
                                                        help="to_be_filled"),
                            'AvghC_avglc_R_util': fields.Float(required = True, 
                                                        description="Promedio de high balance/Promedio de limite de crédito para cuentas revolventes útiles", 
                                                        help="to_be_filled"),
                            'EDAD_N': fields.Float(required = True, 
                                                        description="Variable estandarizada de edad", 
                                                        help="to_be_filled"),
                            'Flag_auto': fields.Integer(required = True, 
                                                        description="Si tiene crédito de auto: 1.-Todos abiertos, 2.-Todos cerrados, 3.- Abiertos y cerrados, 0.- Ninguno", 
                                                        help="to_be_filled"),
                            'Flag_hipo': fields.Integer(required = True, 
                                                        description="Si tiene crédito Hipotecario: 1.-Todos abiertos, 2.-Todos cerrados, 3.- Abiertos y cerrados, 0.- Ninguno", 
                                                        help="to_be_filled"),
                            'Flag_nomina': fields.Integer(required = True, 
                                                        description="Si tiene crédito Nómina: 1.-Todos abiertos, 2.-Todos cerrados, 3.- Abiertos y cerrados, 0.- Ninguno", 
                                                        help="to_be_filled"),
                            'Flag_producto': fields.Integer(required = True, 
                                                        description="Combinaciones de producto: 1.- Tdc, 2.-Auto, 3.-Hipo, 4.-Personales, 5.-Tdc y auto, 6.-Tdc e hipo, 7.-Tdc y personales,8.-auto e hipo,9.-auto y  personales,10.-hipo y personales,11.-tdc,hipo y auto,12.-tdc,hipo y auto,13.-tdc,auto y personales,14.-tdc,hipo y personales,15.-hipo ,auto y personales,16.-todos,17.-ninguno", 
                                                        help="to_be_filled"),
                            'Flag_tdc': fields.Integer(required = True, 
                                                        description="Si tiene crédito de TDC : 1.-Todos abiertos, 2.-Todos cerrados, 3.- Abiertos y cerrados, 0.- Ninguno", 
                                                        help="to_be_filled"),
                            'HghC_r_sldo_R_open': fields.Float(required = True, 
                                                        description="suma(high credit) - suma(saldo actual) para cuentas revolventes abiertas", 
                                                        help="to_be_filled"),
                            'HghC_r_sldo_o': fields.Float(required = True, 
                                                        description="suma(high credit) - suma(saldo actual) para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'HghC_r_sldo_u': fields.Float(required = True, 
                                                        description="suma(high credit) - suma(saldo actual) para cuentas útiles", 
                                                        help="to_be_filled"),
                            'HghC_sldo_R_open': fields.Float(required = True, 
                                                        description="suma(high credit) /suma( saldo actual) para cuentas revolventes abiertas", 
                                                        help="to_be_filled"),
                            'HghC_smlc_R_util': fields.Float(required = True, 
                                                        description="suma(high credit)/ suma limite de crédito para cuentas revolventes útiles", 
                                                        help="to_be_filled"),
                            'Ldis_sdo_act_R_tot': fields.Float(required = True, 
                                                        description="suma saldo actual/suma de la Línea disponible  para cuentas revolventes", 
                                                        help="to_be_filled"),
                            'Limcred_sm2_R_12_open': fields.Float(required = True, 
                                                        description="Limite de crédito sin mop 2 o más, en los últimos 12 meses para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'LmCrd_Smpagos_0': fields.Float(required = True, 
                                                        description="suma(límites de crédito) / suma ponderada de pagos para cuentas revolventes con utilización 0%", 
                                                        help="to_be_filled"),
                            'Lna_disp_open': fields.Float(required = True, 
                                                        description="suma Monto Línea disponible para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'Lna_disp_util': fields.Float(required = True, 
                                                        description="suma Monto Línea disponible para cuentas útiles", 
                                                        help="to_be_filled"),
                            'MaxHghC_smlc_R_open': fields.Float(required = True, 
                                                        description="máximo(high balance / límite de crédito) para cuentas revolventes abiertas", 
                                                        help="to_be_filled"),
                            'MaxHghC_smlc_R_tot': fields.Float(required = True, 
                                                        description="máximo(high balance / límite de crédito) para cuentas revolventes", 
                                                        help="to_be_filled"),
                            'Max_Timsdo0_HIPO': fields.Float(required = True, 
                                                        description="Máximo tiempo desde que tuvo saldo cero para cuentas de HIPOTECARIO", 
                                                        help="to_be_filled"),
                            'Max_Timsdo0_TDC_close': fields.Float(required = True, 
                                                        description="Máximo tiempo desde que tuvo saldo cero para cuentas de TDC cerradas", 
                                                        help="to_be_filled"),
                            'Maxlc_Minlc': fields.Float(required = True, 
                                                        description="Máximo límite de crédito / mínimo límite de crédito", 
                                                        help="to_be_filled"),
                            'Maxlc_Minlc_o': fields.Float(required = True, 
                                                        description="Máximo límite de crédito / mínimo límite de crédito para cuenctas abiertas", 
                                                        help="to_be_filled"),
                            'Maxlc_Minlc_u': fields.Float(required = True, 
                                                        description="Máximo límite de crédito / mínimo límite de crédito para cuentas útiles", 
                                                        help="to_be_filled"),
                            'N_SOLICITUD': fields.Float(required = True, 
                                                        description="Número de solicitud", 
                                                        help="to_be_filled"),
                            'NcLimcred_sm2_12_o': fields.Float(required = True, 
                                                        description="Número de cuentas sin MOP 2+ en los últimos 12 meses para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'NcLimcred_sm2_24': fields.Float(required = True, 
                                                        description="Número de cuentas sin MOP 2+ en los últimos 24 meses", 
                                                        help="to_be_filled"),
                            'Nc_R_util': fields.Float(required = True, 
                                                        description="Numero de cuentas revolventes útiles", 
                                                        help="to_be_filled"),
                            'NormaE12': fields.Float(required = True, 
                                                        description="Norma Euclideana del historial de MOP's de los últimos 12 meses", 
                                                        help="to_be_filled"),
                            'NormaE6_open': fields.Float(required = True, 
                                                        description="Norma Euclideana del historial de MOP's de los últimos 6 meses para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'NormaE_open': fields.Float(required = True, 
                                                        description="Norma Euclideana del historial de MOP's para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'NormaE_util': fields.Float(required = True, 
                                                        description="Norma Euclideana del historial de MOP's para cuentas útiles", 
                                                        help="to_be_filled"),
                            'PDER_ISTE': fields.Float(required = True, 
                                                        description="Población derechohabiente del ISSTE", 
                                                        help="to_be_filled"),
                            'PDER_ISTEE': fields.Float(required = True, 
                                                        description="Población derechohabiente del ISSTE estatal", 
                                                        help="to_be_filled"),
                            'SEXO_N': fields.Float(required = True, 
                                                        description="Variable estandarizada de sexo", 
                                                        help="to_be_filled"),
                            'Sldo_e_sldomx_R_tot': fields.Float(required = True, 
                                                        description="saldo/max(saldo) para cuentas revolventes", 
                                                        help="to_be_filled"),
                            'banderaAuto': fields.Integer(required = True, 
                                                        description="Toma el valor de uno cuando account_type=AU para alguna cuenta, cero en otro caso", 
                                                        help="to_be_filled"),
                            'banderaHipo': fields.Integer(required = True, 
                                                        description="Toma el valor de uno cuando account_type=M para alguna cuenta, cero en otro caso", 
                                                        help="to_be_filled"),
                            'banderapers': fields.Integer(required = True, 
                                                        description="Toma el valor de uno cuando account_type=PL para alguna cuenta, cero en otro caso", 
                                                        help="to_be_filled"),
                            'banderatdc': fields.Integer(required = True, 
                                                        description="Toma el valor de uno cuando account_type=CC para alguna cuenta, cero en otro caso", 
                                                        help="to_be_filled"),
                            'cv_P12A14NOAF': fields.Float(required = True, 
                                                        description="Coeficiente de variación de la población femenina de 12 a 14 años que no asiste a la escuela", 
                                                        help="to_be_filled"),
                            'cv_P15PRI_INM': fields.Float(required = True, 
                                                        description="Coeficiente de variación de la  población masculina de 15 años y más con primaria incompleta", 
                                                        help="to_be_filled"),
                            'cv_P15SEC_INF': fields.Float(required = True, 
                                                        description="Coeficiente de variación de la  población femenina de 15 años y más con primaria incompleta", 
                                                        help="to_be_filled"),
                            'cv_P3A5_NOA_F': fields.Float(required = True, 
                                                        description="Coeficiente de variación de la población femenina  de 3 a 5 años de edad que no van a la escuela", 
                                                        help="to_be_filled"),
                            'cv_PDER_SEGP': fields.Float(required = True, 
                                                        description="Coeficiente de variación de la  población derechohabiente del seguro popular o seguro médico para una nueva generación", 
                                                        help="to_be_filled"),
                            'cv_PSINDER': fields.Float(required = True, 
                                                        description="Coeficiente de variación de la población sin derechohabiencia a servicios de salud", 
                                                        help="to_be_filled"),
                            'cv_VPH_2CUART': fields.Float(required = True, 
                                                        description="Coeficiente de variación de las viviendas particulares habitadas con dos cuartos", 
                                                        help="to_be_filled"),
                            'cv_VPH_AGUAFV': fields.Float(required = True, 
                                                        description="Coeficiente de variación de las viviendas particuales habitadas que no disponen de agua entubada en el ámbito de la vivienda", 
                                                        help="to_be_filled"),
                            'cv_VPH_PISOTI': fields.Float(required = True, 
                                                        description="Coeficiente de variación de las viviendas particulares habitadas con piso de tierra", 
                                                        help="to_be_filled"),
                            'max_GRAPROES_M': fields.Float(required = True, 
                                                        description="Máximo del  Grado promedio de escolaridad de la población masculina", 
                                                        help="to_be_filled"),
                            'max_PCLIM_MEN2': fields.Float(required = True, 
                                                        description="Máximo de las personas con alguna limitación mental", 
                                                        help="to_be_filled"),
                            'max_PDER_ISTE': fields.Float(required = True, 
                                                        description="Máximo de la población derechohabiente del ISSTE", 
                                                        help="to_be_filled"),
                            'max_P_60YMAS': fields.Float(required = True, 
                                                        description="Máximo de la población de 65 años y más", 
                                                        help="to_be_filled"),
                            'max_edad_TDC': fields.Float(required = True, 
                                                        description="Máxima antiguedad en cuenta con TDC", 
                                                        help="to_be_filled"),
                            'max_high_cred_NOM': fields.Float(required = True, 
                                                        description="Max(Credito_maximo) en cuentas de Nómina", 
                                                        help="to_be_filled"),
                            'max_high_cred_TDC': fields.Float(required = True, 
                                                        description="Max(Hight credit) en cuentas de TDC", 
                                                        help="to_be_filled"),
                            'max_lim_cred_NOM': fields.Float(required = True, 
                                                        description="Max(Limite_credito) para cuentas de Nómina", 
                                                        help="to_be_filled"),
                            'max_lim_cred_R_open': fields.Float(required = True, 
                                                        description="Máximo (Limite_credito) para cuentas revolventes abiertas", 
                                                        help="to_be_filled"),
                            'max_lim_cred_R_tot': fields.Float(required = True, 
                                                        description="Máximo (Limite_credito) para cuentas revolventes", 
                                                        help="to_be_filled"),
                            'max_lim_cred_TDC_close': fields.Float(required = True, 
                                                        description="Max(Limite_credito) en cuentas cerradas de TDC", 
                                                        help="to_be_filled"),
                            'max_lim_cred_TDC_open': fields.Float(required = True, 
                                                        description="Máx(Limite_credito) en cuentas abiertas de TDC", 
                                                        help="to_be_filled"),
                            'max_lim_cred_open': fields.Float(required = True, 
                                                        description="Max(Limite_credito) para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'max_max_cred': fields.Float(required = True, 
                                                        description="max(Credito_maximo)", 
                                                        help="to_be_filled"),
                            'max_max_cred_R_tot': fields.Float(required = True, 
                                                        description="Max(Credito_maximo) para cuentas revolventes", 
                                                        help="to_be_filled"),
                            'max_max_cred_open': fields.Float(required = True, 
                                                        description="Máx(High_credit) para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'max_pago_util': fields.Float(required = True, 
                                                        description="Max(saldo) para cuentas útiles ((RE,AF,AU,PN,CL,PL,CC))", 
                                                        help="to_be_filled"),
                            'mdian_lc': fields.Float(required = True, 
                                                        description=" Mediana de los limites de crédito", 
                                                        help="to_be_filled"),
                            'mdian_lc_open': fields.Float(required = True, 
                                                        description="Mediana de los limites de crédito para cuentas abiertas", 
                                                        help="to_be_filled"),
                            'mdian_lc_util': fields.Float(required = True, 
                                                        description="Mediana de los limites de crédito para cuentas útiles", 
                                                        help="to_be_filled"),
                            'mean_GRAPROES_F': fields.Float(required = True, 
                                                        description="Media del grado promedio de escolaridad de la población femenina", 
                                                        help="to_be_filled"),
                            'mean_PCLIM_MOT2': fields.Float(required = True, 
                                                        description="Media de las personas con dificultad para bañarse, vestirse o comer.", 
                                                        help="to_be_filled"),
                            'mean_PDER_ISTE': fields.Float(required = True, 
                                                        description="Media de la población derechohabiente del ISSTE", 
                                                        help="to_be_filled"),
                            'mean_PDESOCUP_F': fields.Float(required = True, 
                                                        description="Media de la población femenina desocupada", 
                                                        help="to_be_filled"),
                            'mean_POTRAS_REL': fields.Float(required = True, 
                                                        description="Media de la población con otras religiones diferentes a la católica y  evangélicas.", 
                                                        help="to_be_filled"),
                            'mean_PSIN_RELIG': fields.Float(required = True, 
                                                        description="Media de la población sin religión", 
                                                        help="to_be_filled"),
                            'meses_ctas_TDC_open': fields.Float(required = True, 
                                                        description="Meses en cuentas abiertas de TDC", 
                                                        help="to_be_filled"),
                            'min_edad_NOM': fields.Float(required = True, 
                                                        description="Mínima edad en meses, en cuenta de nómina", 
                                                        help="to_be_filled"),
                            'min_edad_NOM_open': fields.Float(required = True, 
                                                        description="Mínima edad en meses, en cuenta de nómina abiertas", 
                                                        help="to_be_filled"),
                            'min_lim_cred': fields.Float(required = True, 
                                                        description="Minimo(Limite_credito)", 
                                                        help="to_be_filled"),
                            'min_lim_cred_R_tot': fields.Float(required = True, 
                                                        description="Minimo(Limite_credito)", 
                                                        help="to_be_filled"),
                            'saldo_act': fields.Float(required = True, 
                                                        description="Suma(Saldos)", 
                                                        help="to_be_filled"),
                            'saldo_act_open': fields.Float(required = True, 
                                                        description="Suma(saldos) cuentas abiertas", 
                                                        help="to_be_filled"),
                            'smHb_r_smldo_TDC_close': fields.Float(required = True, 
                                                        description="[suma(Credito_maximo)-suma(saldo actual)] para cuentas de TDC cerradas", 
                                                        help="to_be_filled"),
                            'sm_hb_HIPO': fields.Float(required = True, 
                                                        description="Suma(Credito_maximo) para cuentas de HIPOTECARIO", 
                                                        help="to_be_filled"),
                            'sm_pag_min_R_tot': fields.Float(required = True, 
                                                        description="Suma(Pago mínimo) para cuentas revolventes", 
                                                        help="to_be_filled"),
                            'sm_sld_act_TDC': fields.Float(required = True, 
                                                        description="Suma (saldo actual) para TDC", 
                                                        help="to_be_filled"),
                            'std_GRAPROES_M': fields.Float(required = True, 
                                                        description="Desviación estandar del grado promedio de escolaridad de la población masculina", 
                                                        help="to_be_filled"),
                            'std_VPH_1CUART': fields.Float(required = True, 
                                                        description="Desviación estandar de las viviendas particulares habitadas con un solo cuarto", 
                                                        help="to_be_filled"),
                            'sum_pag_edad_u': fields.Float(required = True, 
                                                        description="suma(pago_reportado/edad de la cuenta)", 
                                                        help="to_be_filled")
                            }
                  )

# @api.route("/predict")
@high_income.route("/predict")
class IncomeRegressorHigh(Resource):
    """Resource endpoint to predict high-risk level client´s income
    """
    def get(self):
        pass
    
    @api.expect(model_fields, validate=True)
    # @api.marshal_with(model_fields, code=200)
    def post(self):
        return {
                "status": "Success", 
                "score": 0.1}
        
@medium_income.route("/predict")
class IncomeRegressorMedium(Resource):
    """Resource endpoint to predict medium-risk level client´s income
    """
    def get(self):
        pass
    
    @api.expect(model_fields, validate=True)
    def post(self):
        return {
                "status": "Success", 
                "score": 0.5}
        
@low_income.route("/predict")
class IncomeRegressorLow(Resource):
    """Resource endpoint to predict low-risk level client´s income
    """
    def get(self):
        pass
    
    @api.expect(model_fields, validate=True)
    def post(self):
        return {
                "status": "Success", 
                "score": 0.9}

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True)